- JOB: intercept $DEVNODE | hideaway 4 10000 10000 -512 -256 | uinput -d $DEVNODE
  DEVICE:
    EVENTS:
      EV_REL: [REL_X, REL_Y]
- JOB: "intercept -g $DEVNODE | dual-function-keys -c /etc/interception/dual-function-keys/remotecontrol.yaml | uinput -d $DEVNODE"
  DEVICE:
    EVENTS:
      EV_KEY: [582, KEY_ENTER]
